theme: jekyll-theme-hacker
title: Mac-Configuration
plugins:
  - jemoji
  - jekyll-seo-tag
  - github-pages-health-check
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-sitemap


relative_links:
  enabled:     true
  collections: true

readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
