theme: jekyll-theme-hacker
title: Mac-Configuration
plugins:
  - jemoji
  - jekyll-seo-tag
  - github-pages-health-check
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-relative-links


relative_links:
  enabled:     true
  collections: false
